export const poeticForm = [
  { value: "Acrostic", label: "Acrostic" },
  { value: "Ballad", label: "Ballad" },
  { value: "Blank Verse", label: "Blank Verse" },
  { value: "Block Form", label: "Block Form" },
  { value: "Canto", label: "Canto" },
  { value: "Canzone", label: "Canzone" },
  { value: "Cinquain", label: "Cinquain" },
  { value: "Couplets", label: "Couplets" },
  { value: "Diamante", label: "Diamante" },
  { value: "Dramatic Monologue", label: "Dramatic Monologue" },
  { value: "Epistle", label: "Epistle" },
  { value: "Erasure Poem", label: "Erasure Poem" },
  { value: "Free Verse", label: "Free Verse" },
  { value: "Ghazal", label: "Ghazal" },
  { value: "Haiku", label: "Haiku" },
  { value: "Hymn", label: "Hymn" },
  { value: "Limerick", label: "Limerick" },
  { value: "Miltonic Sonnet", label: "Miltonic Sonnet" },
  { value: "Narrative", label: "Narrative" },
  { value: "Octave", label: "Octave" },
  { value: "Ode", label: "Ode" },
  { value: "Ottava Rima", label: "Ottava Rima" },
  { value: "Petrarchan Sonnet", label: "Petrarchan Sonnet" },
  { value: "Quatrain", label: "Quatrain" },
  { value: "Rondel", label: "Rondel" },
  { value: "Sestet", label: "Sestet" },
  { value: "Sestina", label: "Sestina" },
  { value: "Shakespearean Sonnet", label: "Shakespearean Sonnet" },
  { value: "Slam Poem", label: "Slam Poem" },
  { value: "Sonnet", label: "Sonnet" },
  { value: "Spenserian Sonnet", label: "Spenserian Sonnet" },
  { value: "Tanka", label: "Tanka" },
  { value: "Terza Rima", label: "Terza Rima" },
  { value: "Villanelle", label: "Villanelle" },
];

export const creativityLevels = [
  { value: "Low", label: "Low" },
  { value: "Medium", label: "Medium" },
  { value: "High", label: "High" },
];

export const poemLengths = [
  { value: "Long (30+ lines)", label: "Long (30+ lines)" },
  { value: "Medium (10-30 lines)", label: "Medium (10-30 lines)" },
  { value: "Short (5-10 lines)", label: "Short (5-10 lines)" },
];

export const syllableCounts = [
  { value: "Any", label: "Any" },
  { value: "4", label: "4" },
  { value: "5", label: "5" },
  { value: "6", label: "6" },
  { value: "7", label: "7" },
  { value: "8", label: "8" },
  { value: "9", label: "9" },
  { value: "10", label: "10" },
  { value: "11", label: "11" },
  { value: "12", label: "12" },
];

export const tones = [
  { value: "Dramatic", label: "Dramatic" },
  { value: "Dark", label: "Dark" },
  { value: "Energetic", label: "Energetic" },
  { value: "Hopeful", label: "Hopeful" },
  { value: "Humorous", label: "Humorous" },
  { value: "Inspirational", label: "Inspirational" },
  { value: "Ironic", label: "Ironic" },
  { value: "Lighthearted", label: "Lighthearted" },
  { value: "Melancholic", label: "Melancholic" },
  { value: "Mysterious", label: "Mysterious" },
  { value: "Nostalgic", label: "Nostalgic" },
  { value: "Optimistic", label: "Optimistic" },
  { value: "Playful", label: "Playful" },
  { value: "Reflective", label: "Reflective" },
  { value: "Romantic", label: "Romantic" },
  { value: "Serene", label: "Serene" },
  { value: "Serious", label: "Serious" },
  { value: "Surreal", label: "Surreal" },
  { value: "Thoughtful", label: "Thoughtful" },
  { value: "Whimsical", label: "Whimsical" },
];

export const themes = [
  { value: "Aging", label: "Aging" },
  { value: "Beauty", label: "Beauty" },
  { value: "Birth", label: "Birth" },
  { value: "Celebration", label: "Celebration" },
  { value: "Coming of Age", label: "Coming of Age" },
  { value: "Death", label: "Death" },
  { value: "Desire", label: "Desire" },
  { value: "Disappointment", label: "Disappointment" },
  { value: "Dreams", label: "Dreams" },
  { value: "Failure", label: "Failure" },
  { value: "Identity", label: "Identity" },
  { value: "Immortality", label: "Immortality" },
  { value: "Journey", label: "Journey" },
  { value: "Love", label: "Love" },
  { value: "Nature", label: "Nature" },
  { value: "New Life", label: "New Life" },
  { value: "Recovery", label: "Recovery" },
  { value: "Relationships", label: "Relationships" },
  { value: "Religion", label: "Religion" },
  { value: "Spirituality", label: "Spirituality" },
  { value: "War", label: "War" },
  { value: "Wellness", label: "Wellness" },
];

export const favoritePoets = [
  { value: "William Cullen Bryant", label: "William Cullen Bryant" },
  { value: "Emily Dickinson", label: "Emily Dickinson" },
  { value: "Paul Laurence Dunbar", label: "Paul Laurence Dunbar" },
  { value: "Ralph Waldo Emerson", label: "Ralph Waldo Emerson" },
  { value: "Philip Freneau", label: "Philip Freneau" },
  { value: "Robert Frost", label: "Robert Frost" },
  {
    value: "Frances Ellen Watkins Harper",
    label: "Frances Ellen Watkins Harper",
  },
  { value: "Oliver Wendell Holmes Sr.", label: "Oliver Wendell Holmes Sr." },
  { value: "Georgia Douglas Johnson", label: "Georgia Douglas Johnson" },
  { value: "James Weldon Johnson", label: "James Weldon Johnson" },
  { value: "Emma Lazarus", label: "Emma Lazarus" },
  { value: "Sidney Lanier", label: "Sidney Lanier" },
  { value: "Henry Wadsworth Longfellow", label: "Henry Wadsworth Longfellow" },
  { value: "Amy Lowell", label: "Amy Lowell" },
  { value: "James Russell Lowell", label: "James Russell Lowell" },
  { value: "Edgar Allan Poe", label: "Edgar Allan Poe" },
  { value: "Edwin Arlington Robinson", label: "Edwin Arlington Robinson" },
  { value: "Lydia Huntley Sigourney", label: "Lydia Huntley Sigourney" },
  { value: "Sara Teasdale", label: "Sara Teasdale" },
  { value: "Phillis Wheatley", label: "Phillis Wheatley" },
  { value: "Walt Whitman", label: "Walt Whitman" },
  { value: "John Greenleaf Whittier", label: "John Greenleaf Whittier" },
];

export const onomatopoeiaWords = [
  { value: "Buzz", label: "Buzz" },
  { value: "Hiss", label: "Hiss" },
  { value: "Splash", label: "Splash" },
  { value: "Crackle", label: "Crackle" },
  { value: "Whir", label: "Whir" },
  { value: "Thud", label: "Thud" },
  { value: "Rustle", label: "Rustle" },
  { value: "Gurgle", label: "Gurgle" },
  { value: "Whoosh", label: "Whoosh" },
  { value: "Clink", label: "Clink" },
  { value: "Sizzle", label: "Sizzle" },
  { value: "Plop", label: "Plop" },
  { value: "Swish", label: "Swish" },
  { value: "Crunch", label: "Crunch" },
  { value: "Chirp", label: "Chirp" },
  { value: "Rumble", label: "Rumble" },
  { value: "Slurp", label: "Slurp" },
  { value: "Clang", label: "Clang" },
  { value: "Pitter-patter", label: "Pitter-patter" },
  { value: "Snap", label: "Snap" },
  { value: "Boom", label: "Boom" },
  { value: "Tick-tock", label: "Tick-tock" },
  { value: "Squeak", label: "Squeak" },
  { value: "Swoosh", label: "Swoosh" },
  { value: "Moo", label: "Moo" },
  { value: "Meow", label: "Meow" },
  { value: "Baa", label: "Baa" },
  { value: "Purr", label: "Purr" },
  { value: "Drip", label: "Drip" },
  { value: "Honk", label: "Honk" },
];

export const rhymeSchemes = [
  { value: "None", label: "None" },
  { value: "ABAB", label: "ABAB" },
  { value: "AABB", label: "AABB" },
  { value: "ABBA", label: "ABBA" },
  { value: "ABCB", label: "ABCB" },
];

export const genres = [
  { value: "Adventure", label: "Adventure" },
  { value: "Allegory", label: "Allegory" },
  { value: "Aubade", label: "Aubade" },
  { value: "Bildungsroman", label: "Bildungsroman" },
  { value: "Blason", label: "Blason" },
  { value: "Cento", label: "Cento" },
  { value: "Comedy", label: "Comedy" },
  { value: "Confessional", label: "Confessional" },
  { value: "Dirge", label: "Dirge" },
  { value: "Dystopia", label: "Dystopia" },
  { value: "Eclogue", label: "Eclogue" },
  { value: "Ekphrasis", label: "Ekphrasis" },
  { value: "Elegy", label: "Elegy" },
  { value: "Epic", label: "Epic" },
  { value: "Epigram", label: "Epigram" },
  { value: "Epitaph", label: "Epitaph" },
  { value: "Epithalamion", label: "Epithalamion" },
  { value: "Fable", label: "Fable" },
  { value: "Fairy Tale", label: "Fairy Tale" },
  { value: "Fantasy", label: "Fantasy" },
  { value: "Folklore", label: "Folklore" },
  { value: "Georgic", label: "Georgic" },
  { value: "Gothic", label: "Gothic" },
  { value: "Invective", label: "Invective" },
  { value: "Lament", label: "Lament" },
  { value: "Legend", label: "Legend" },
  { value: "Light Verse", label: "Light Verse" },
  { value: "Lyric", label: "Lyric" },
  { value: "Magical Realism", label: "Magical Realism" },
  { value: "Masque", label: "Masque" },
  { value: "Mystery", label: "Mystery" },
  { value: "Nursery Rhyme", label: "Nursery Rhyme" },
  { value: "Occasional Verse", label: "Occasional Verse" },
  { value: "Paean", label: "Paean" },
  { value: "Palinode", label: "Palinode" },
  { value: "Panegyric", label: "Panegyric" },
  { value: "Parody", label: "Parody" },
  { value: "Pastoral", label: "Pastoral" },
  { value: "Prose", label: "Prose" },
  { value: "Psalm", label: "Psalm" },
  { value: "Riddle", label: "Riddle" },
  { value: "Romance", label: "Romance" },
  { value: "Satire", label: "Satire" },
  { value: "Tragedy", label: "Tragedy" },
];

export const topics = [
  { value: "Adulthood", label: "Adulthood" },
  { value: "Adversity", label: "Adversity" },
  { value: "African Americans", label: "African Americans" },
  { value: "African Culture", label: "African Culture" },
  { value: "Afterlife", label: "Afterlife" },
  { value: "Alliteration", label: "Alliteration" },
  { value: "Allusion", label: "Allusion" },
  { value: "Ambition", label: "Ambition" },
  { value: "Angels", label: "Angels" },
  { value: "Animals", label: "Animals" },
  { value: "Apocalypse", label: "Apocalypse" },
  { value: "Appreciation", label: "Appreciation" },
  { value: "Art", label: "Art" },
  { value: "Aunties", label: "Aunties" },
  { value: "Autumn", label: "Autumn" },
  { value: "Babies", label: "Babies" },
  { value: "Baseball", label: "Baseball" },
  { value: "Basketball", label: "Basketball" },
  { value: "Being Yourself", label: "Being Yourself" },
  { value: "Betrayal", label: "Betrayal" },
  { value: "Birds", label: "Birds" },
  { value: "Birthdays", label: "Birthdays" },
  { value: "Blindness", label: "Blindness" },
  { value: "Blues", label: "Blues" },
  { value: "Body Image", label: "Body Image" },
  { value: "Books", label: "Books" },
  { value: "Breaking Up", label: "Breaking Up" },
  { value: "Brothers", label: "Brothers" },
  { value: "Bullying", label: "Bullying" },
  { value: "Butterflies", label: "Butterflies" },
  { value: "Care", label: "Care" },
  { value: "Cats", label: "Cats" },
  { value: "Change", label: "Change" },
  { value: "Chaos", label: "Chaos" },
  { value: "Cheaters", label: "Cheaters" },
  { value: "Chickens", label: "Chickens" },
  { value: "Childhood", label: "Childhood" },
  { value: "Chocolate", label: "Chocolate" },
  { value: "Choice", label: "Choice" },
  { value: "Christmas", label: "Christmas" },
  { value: "Climate Change", label: "Climate Change" },
  { value: "Clouds", label: "Clouds" },
  { value: "Coffee", label: "Coffee" },
  { value: "Colors", label: "Colors" },
  { value: "Communication", label: "Communication" },
  { value: "Community", label: "Community" },
  { value: "Conflict", label: "Conflict" },
  { value: "Cooking", label: "Cooking" },
  { value: "Coronavirus", label: "Coronavirus" },
  { value: "Corruption", label: "Corruption" },
  { value: "Countryside", label: "Countryside" },
  { value: "Cousins", label: "Cousins" },
  { value: "Creativity", label: "Creativity" },
  { value: "Crying", label: "Crying" },
  { value: "Culture", label: "Culture" },
  { value: "Daily Life", label: "Daily Life" },
  { value: "Dance", label: "Dance" },
  { value: "Danger", label: "Danger" },
  { value: "Darkness", label: "Darkness" },
  { value: "Daughters", label: "Daughters" },
  { value: "Death of a Loved One", label: "Death of a Loved One" },
  { value: "Dementia", label: "Dementia" },
  { value: "Demons", label: "Demons" },
  { value: "Devotion", label: "Devotion" },
  { value: "Discrimination", label: "Discrimination" },
  { value: "Doctors and Nurses", label: "Doctors and Nurses" },
  { value: "Dogs", label: "Dogs" },
  { value: "Doors", label: "Doors" },
  { value: "Dragons", label: "Dragons" },
  { value: "Drinks", label: "Drinks" },
  { value: "Drowning", label: "Drowning" },
  { value: "Drug Addictions", label: "Drug Addictions" },
  { value: "Earth", label: "Earth" },
  { value: "Education", label: "Education" },
  { value: "Elephants", label: "Elephants" },
  { value: "Epiphany", label: "Epiphany" },
  { value: "Equality", label: "Equality" },
  { value: "Evening", label: "Evening" },
  { value: "Evil", label: "Evil" },
  { value: "Exploration", label: "Exploration" },
  { value: "Eyes", label: "Eyes" },
  { value: "Family", label: "Family" },
  { value: "Farms", label: "Farms" },
  { value: "Fate", label: "Fate" },
  { value: "Fatherhood", label: "Fatherhood" },
  { value: "Feminism", label: "Feminism" },
  { value: "Fighting", label: "Fighting" },
  { value: "Fire", label: "Fire" },
  { value: "Fireworks", label: "Fireworks" },
  { value: "Fish", label: "Fish" },
  { value: "Flowers", label: "Flowers" },
  { value: "Flying", label: "Flying" },
  { value: "Fog", label: "Fog" },
  { value: "Food", label: "Food" },
  { value: "Football", label: "Football" },
  { value: "Forests", label: "Forests" },
  { value: "Forgiveness", label: "Forgiveness" },
  { value: "Friendship", label: "Friendship" },
  { value: "Future", label: "Future" },
  { value: "Games", label: "Games" },
  { value: "Gardening", label: "Gardening" },
  { value: "Gardens", label: "Gardens" },
  { value: "Generosity", label: "Generosity" },
  { value: "Getting Back Together", label: "Getting Back Together" },
  { value: "Ghosts", label: "Ghosts" },
  { value: "Gold", label: "Gold" },
  { value: "Graduation", label: "Graduation" },
  { value: "Grandchildren", label: "Grandchildren" },
  { value: "Grandparents", label: "Grandparents" },
  { value: "Haircuts", label: "Haircuts" },
  { value: "Halloween", label: "Halloween" },
  { value: "Hard Times", label: "Hard Times" },
  { value: "Hard Workers", label: "Hard Workers" },
  { value: "Harvesting", label: "Harvesting" },
  { value: "Hatred", label: "Hatred" },
  { value: "Health", label: "Health" },
  { value: "Heartbreak", label: "Heartbreak" },
  { value: "Heaven", label: "Heaven" },
  { value: "Hell", label: "Hell" },
  { value: "Heroism", label: "Heroism" },
  { value: "History", label: "History" },
  { value: "Home", label: "Home" },
  { value: "Homelessness", label: "Homelessness" },
  { value: "Homosexuality", label: "Homosexuality" },
  { value: "Horses", label: "Horses" },
  { value: "Hospital", label: "Hospital" },
  { value: "Humanity", label: "Humanity" },
  { value: "Humanity vs Nature", label: "Humanity vs Nature" },
  { value: "Ice", label: "Ice" },
  { value: "Illness", label: "Illness" },
  { value: "Imagination", label: "Imagination" },
  { value: "Immigration", label: "Immigration" },
  { value: "Imprisonment", label: "Imprisonment" },
  { value: "Independence", label: "Independence" },
  { value: "Industrialisation", label: "Industrialisation" },
  { value: "Injustice", label: "Injustice" },
  { value: "Inner Beauty", label: "Inner Beauty" },
  { value: "Innocence", label: "Innocence" },
  { value: "Insects", label: "Insects" },
  { value: "Insecurity", label: "Insecurity" },
  { value: "Inspiration", label: "Inspiration" },
  { value: "Irony", label: "Irony" },
  { value: "Islands", label: "Islands" },
  { value: "Isolation", label: "Isolation" },
  { value: "Justice", label: "Justice" },
  { value: "Keys", label: "Keys" },
  { value: "Kings and Queens", label: "Kings and Queens" },
  { value: "Kissing", label: "Kissing" },
  { value: "Knitting", label: "Knitting" },
  { value: "Knowledge", label: "Knowledge" },
  { value: "Leaders", label: "Leaders" },
  { value: "LGBTQ", label: "LGBTQ" },
  { value: "Libraries", label: "Libraries" },
  { value: "Life", label: "Life" },
  { value: "Life Lessons", label: "Life Lessons" },
  { value: "Life Struggles", label: "Life Struggles" },
  { value: "Light", label: "Light" },
  { value: "Lions", label: "Lions" },
  { value: "London", label: "London" },
  { value: "Loss", label: "Loss" },
  { value: "Loving Yourself", label: "Loving Yourself" },
  { value: "Madness", label: "Madness" },
  { value: "Making Decisions", label: "Making Decisions" },
  { value: "Marriage", label: "Marriage" },
  { value: "Meditation", label: "Meditation" },
  { value: "Memories", label: "Memories" },
  { value: "Memory", label: "Memory" },
  { value: "Mermaids", label: "Mermaids" },
  { value: "Metaphor", label: "Metaphor" },
  { value: "Mistakes", label: "Mistakes" },
  { value: "Money", label: "Money" },
  { value: "Monsters", label: "Monsters" },
  { value: "Mornings", label: "Mornings" },
  { value: "Mortality", label: "Mortality" },
  { value: "Motherhood", label: "Motherhood" },
  { value: "Mountains", label: "Mountains" },
  { value: "Mourning", label: "Mourning" },
  { value: "Music", label: "Music" },
  { value: "Mythology", label: "Mythology" },
  { value: "New Beginnings", label: "New Beginnings" },
  { value: "New Year", label: "New Year" },
  { value: "Night", label: "Night" },
  { value: "Nostalgia", label: "Nostalgia" },
  { value: "Overcoming Adversity", label: "Overcoming Adversity" },
  { value: "Owls", label: "Owls" },
  { value: "Paintings", label: "Paintings" },
  { value: "Parenthood", label: "Parenthood" },
  { value: "Peace", label: "Peace" },
  { value: "Perseverance", label: "Perseverance" },
  { value: "Personification", label: "Personification" },
  { value: "Pets", label: "Pets" },
  { value: "Philosophical", label: "Philosophical" },
  { value: "Phones", label: "Phones" },
  { value: "Pizza", label: "Pizza" },
  { value: "Plants", label: "Plants" },
  { value: "Poets", label: "Poets" },
  { value: "Politics", label: "Politics" },
  { value: "Poppies", label: "Poppies" },
  { value: "Positivity", label: "Positivity" },
  { value: "Poverty", label: "Poverty" },
  { value: "Power", label: "Power" },
  { value: "Prayer", label: "Prayer" },
  { value: "Pregnancy", label: "Pregnancy" },
  { value: "Presidents", label: "Presidents" },
  { value: "Prison", label: "Prison" },
  { value: "PTSD", label: "PTSD" },
  { value: "Racism", label: "Racism" },
  { value: "Rain", label: "Rain" },
  { value: "Rainbows", label: "Rainbows" },
  { value: "Retiring", label: "Retiring" },
  { value: "Rivers", label: "Rivers" },
  { value: "Roses", label: "Roses" },
  { value: "Sailing", label: "Sailing" },
  { value: "School", label: "School" },
  { value: "Science", label: "Science" },
  { value: "Sea", label: "Sea" },
  { value: "Seasons", label: "Seasons" },
  { value: "Secrets", label: "Secrets" },
  { value: "Self-Love", label: "Self-Love" },
  { value: "Selfishness", label: "Selfishness" },
  { value: "Sewing", label: "Sewing" },
  { value: "Sexism", label: "Sexism" },
  { value: "Sexuality", label: "Sexuality" },
  { value: "Sharks", label: "Sharks" },
  { value: "Sickness", label: "Sickness" },
  { value: "Silence", label: "Silence" },
  { value: "Singing", label: "Singing" },
  { value: "Sisters", label: "Sisters" },
  { value: "Sky", label: "Sky" },
  { value: "Sleep", label: "Sleep" },
  { value: "Snow", label: "Snow" },
  { value: "Soccer", label: "Soccer" },
  { value: "Socks", label: "Socks" },
  { value: "Solitude", label: "Solitude" },
  { value: "Soul", label: "Soul" },
  { value: "Space", label: "Space" },
  { value: "Sports", label: "Sports" },
  { value: "Spring", label: "Spring" },
  { value: "Stars", label: "Stars" },
  { value: "Starting Over", label: "Starting Over" },
  { value: "Stones", label: "Stones" },
  { value: "Storms", label: "Storms" },
  { value: "Strength", label: "Strength" },
  { value: "Success", label: "Success" },
  { value: "Summer", label: "Summer" },
  { value: "Sun", label: "Sun" },
  { value: "Sunrises", label: "Sunrises" },
  { value: "Sunsets", label: "Sunsets" },
  { value: "Sweets", label: "Sweets" },
  { value: "Thanksgiving", label: "Thanksgiving" },
  { value: "The Past", label: "The Past" },
  { value: "Tigers", label: "Tigers" },
  { value: "Time", label: "Time" },
  { value: "Transformation", label: "Transformation" },
  { value: "Travel", label: "Travel" },
  { value: "Treasure", label: "Treasure" },
  { value: "Trees", label: "Trees" },
  { value: "Trust", label: "Trust" },
  { value: "Uncertainty", label: "Uncertainty" },
  { value: "Unicorns", label: "Unicorns" },
  { value: "Universe", label: "Universe" },
  { value: "Vampires", label: "Vampires" },
  { value: "Vegetables", label: "Vegetables" },
  { value: "Vikings", label: "Vikings" },
  { value: "Volcanoes", label: "Volcanoes" },
  { value: "Volunteering", label: "Volunteering" },
  { value: "Waiting", label: "Waiting" },
  { value: "Walking", label: "Walking" },
  { value: "Water", label: "Water" },
  { value: "Wealth", label: "Wealth" },
  { value: "Weather", label: "Weather" },
  { value: "Wind", label: "Wind" },
  { value: "Wine", label: "Wine" },
  { value: "Winning", label: "Winning" },
  { value: "Winter", label: "Winter" },
  { value: "Women", label: "Women" },
  { value: "Working", label: "Working" },
  { value: "Youth", label: "Youth" },
  { value: "Zebras", label: "Zebras" },
];

export const emotionsEvoked = [
  { value: "Abandonment", label: "Abandonment" },
  { value: "Amusement", label: "Amusement" },
  { value: "Anger", label: "Anger" },
  { value: "Anxiety", label: "Anxiety" },
  { value: "Boredom", label: "Boredom" },
  { value: "Bravery", label: "Bravery" },
  { value: "Compassion", label: "Compassion" },
  { value: "Confidence", label: "Confidence" },
  { value: "Confusion", label: "Confusion" },
  { value: "Contentment", label: "Contentment" },
  { value: "Courage", label: "Courage" },
  { value: "Depression", label: "Depression" },
  { value: "Disgust", label: "Disgust" },
  { value: "Dishonesty", label: "Dishonesty" },
  { value: "Empathy", label: "Empathy" },
  { value: "Enjoyment", label: "Enjoyment" },
  { value: "Excitement", label: "Excitement" },
  { value: "Faith", label: "Faith" },
  { value: "Fear", label: "Fear" },
  { value: "Freedom", label: "Freedom" },
  { value: "Frustration", label: "Frustration" },
  { value: "Happiness", label: "Happiness" },
  { value: "Honor", label: "Honor" },
  { value: "Hope", label: "Hope" },
  { value: "Hopelessness", label: "Hopelessness" },
  { value: "Jealousy", label: "Jealousy" },
  { value: "Joyfulness", label: "Joyfulness" },
  { value: "Kindness", label: "Kindness" },
  { value: "Laughter", label: "Laughter" },
  { value: "Missing Someone", label: "Missing Someone" },
  { value: "Nervousness", label: "Nervousness" },
  { value: "Optimism", label: "Optimism" },
  { value: "Pain", label: "Pain" },
  { value: "Panic", label: "Panic" },
  { value: "Passion", label: "Passion" },
  { value: "Pessimism", label: "Pessimism" },
  { value: "Pride", label: "Pride" },
  { value: "Regret", label: "Regret" },
  { value: "Relief", label: "Relief" },
  { value: "Remorse", label: "Remorse" },
  { value: "Resilience", label: "Resilience" },
  { value: "Sadness", label: "Sadness" },
  { value: "Satisfaction", label: "Satisfaction" },
  { value: "Stress", label: "Stress" },
  { value: "Sympathy", label: "Sympathy" },
  { value: "Terror", label: "Terror" },
  { value: "Vengeance", label: "Vengeance" },
  { value: "Worry", label: "Worry" },
];
